config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  resources :characters, shallow: true do
    resources :items
  end
  resources :room_characters
  resources :visitors
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

end

app/models/visitor.rb
class Visitor < ApplicationRecord
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: [:show, :edit, :update, :destroy]

  # GET /visitors
  # GET /visitors.json
  def index
    @visitors = Visitor.all
  end

  # GET /visitors/1
  # GET /visitors/1.json
  def show
  end

  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
  end

  # POST /visitors
  # POST /visitors.json
  def create
    @visitor = Visitor.new(visitor_params)

    respond_to do |format|
      if @visitor.save
        DeliveryNotificationMailer.welcome(@visitor).deliver
        format.html { redirect_to @visitor, notice: 'Visitor was successfully created.' }
        format.json { render :show, status: :created, location: @visitor }
      else
        format.html { render :new }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitors/1
  # PATCH/PUT /visitors/1.json
  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to @visitor, notice: 'Visitor was successfully updated.' }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1
  # DELETE /visitors/1.json
  def destroy
    @visitor.destroy
    respond_to do |format|
      format.html { redirect_to visitors_url, notice: 'Visitor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visitor_params
      params.require(:visitor).permit(:first_name, :last_name, :email, :phone, :message)
    end
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/visitors/_form.html.erb
<%= simple_form_for(@visitor) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.input :first_name %>

    <%= f.input :last_name %>

    <%= f.input :email %>

    <%= f.input :phone %>

    <%= f.input :message %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/visitors/edit.html.erb
<h1>Editing Visitor</h1>

<%= render 'form', visitor: @visitor %>

<%= link_to 'Show', @visitor %> |
<%= link_to 'Back', visitors_path %>

app/views/visitors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Visitors</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visitors.each do |visitor| %>
      <tr>
        <td><%= visitor.first_name %></td>
        <td><%= visitor.last_name %></td>
        <td><%= visitor.email %></td>
        <td><%= visitor.phone %></td>
        <td><%= visitor.message %></td>
        <td><%= link_to 'Show', visitor %></td>
        <td><%= link_to 'Edit', edit_visitor_path(visitor) %></td>
        <td><%= link_to 'Destroy', visitor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visitor', new_visitor_path %>

app/views/visitors/new.html.erb
<h1>New Visitor</h1>

<%= render 'form', visitor: @visitor %>

<%= link_to 'Back', visitors_path %>

app/views/visitors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @visitor.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @visitor.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @visitor.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @visitor.phone %>
</p>

<p>
  <strong>Message:</strong>
  <%= @visitor.message %>
</p>

<%= link_to 'Edit', edit_visitor_path(@visitor) %> |
<%= link_to 'Back', visitors_path %>