config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  resources :characters, shallow: true do
    resources :items
  end
  resources :room_characters
  resources :visitors
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

end

app/models/character.rb
class Character < ApplicationRecord
   belongs_to :user
   has_many :items, dependent: :destroy
   has_many :campaigns, class_name: "RoomCharacter", foreign_key: "player_id"

   validates :name, :job, :level, presence: true

   def stat_mod(stat)
     stat / 2 - 5
   end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  # GET /characters
  # GET /characters.json
  def index
        @characters = current_user.characters
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = current_user.characters.build
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create

    initiative_bonus = set_initiative
    updated_params = character_params.merge(initiative: initiative_bonus)
    @character = current_user.characters.build(updated_params)
    @character.user = current_user

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update

    initiative_bonus = set_initiative
    updated_params = character_params.merge(initiative: initiative_bonus)

    respond_to do |format|
      if @character.update(updated_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

   def set_initiative
     dex_mod = character_params[:dexterity].to_i / 2 - 5
     if character_params[:improved_initiative] == "1"
       initiative_bonus = dex_mod.to_i + character_params[:level].to_i + 4
     else
       initiative_bonus = dex_mod.to_i + character_params[:level].to_i
     end
   end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
       params.require(:character).permit(:name, :race, :job, :level, :strength, :constitution, :dexterity, :intelligence, :wisdom, :charisma, :armor_class, :phys_def, :mental_def, :hit_points, :recoveries, :recovery_dice, :one_unique_thing, :icons, :backgrounds, :racial, :class_features, :talents, :melee_atk, :ranged_atk, :powers, :feats, :improved_initiative, :equipment, :gold, :initiative, :user_id)
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= simple_form_for(character, html: { class: 'form-vertical' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :race %>
    <%= f.input :job %>
    <%= f.input :level %>
    <%= f.input :strength %>
    <%= f.input :constitution %>
    <%= f.input :dexterity %>
    <%= f.input :intelligence %>
    <%= f.input :wisdom %>
    <%= f.input :charisma %>
    <%= f.input :armor_class %>
    <%= f.input :phys_def %>
    <%= f.input :mental_def %>
    <%= f.input :hit_points %>
    <%= f.input :recoveries %>
    <%= f.input :recovery_dice %>
    <%= f.input :one_unique_thing %>
    <%= f.input :icons %>
    <%= f.input :backgrounds %>
    <%= f.input :racial %>
    <%= f.input :class_features %>
    <%= f.input :talents %>
    <%= f.input :melee_atk %>
    <%= f.input :ranged_atk %>
    <%= f.input :powers %>
    <%= f.input :feats %>
    <%= f.input :improved_initiative %>
    <%= f.input :equipment %>
    <%= f.input :gold %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character Sheet</h1>

<%= render 'form', character: @character %>

<%= link_to 'View character', @character %> |
<%= link_to 'Character index', characters_path %>

app/views/characters/index.html.erb
<p id="notice" class="text-center"><%= notice %></p>

<h1>Characters</h1>

<% if @characters.present? %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Class</th>
        <th>Level</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @characters.each do |character| %>
        <tr>
          <td><%= character.name %> </td>
          <td><%= character.job %></td>
          <td><%= character.level %></td>

          <td><%= link_to 'View', character %></td>
          <td><%= link_to 'Inventory', character_items_path(character.id) %></td>
          <td><%= link_to 'Edit', edit_character_path(character) %></td>
          <td><%= link_to 'Remove', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No characters added</p>
<% end %>

<br>

<%= link_to 'Add a character', new_character_path %>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice" class="text-center"><%= notice %></p>

<div class="row">
  <div class="panel panel-default text-center">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @character.name %>'s Character Sheet</h3>
    </div>
    <div class="panel-body">
        <p>
          <strong>Name:</strong>
          <%= @character.name %> |
          <strong>Level:</strong>
          <%= @character.level %>
        </p>

        <p>
          <strong>Class:</strong>
          <%= @character.job %> |
          <strong>Race:</strong>
          <%= @character.race %>
        </p>
        <p>
          <strong>Str:</strong>
          <%= @character.strength %> |
          Mod:
          <%= @character.strength / 2 - 5 %>
        </p>

        <p>
          <strong>Con:</strong>
          <%= @character.constitution %> |
          Mod:
          <%= @character.constitution / 2 - 5 %>
        </p>

        <p>
          <strong>Dex:</strong>
          <%= @character.dexterity %> |
          Mod:
          <%= @character.dexterity / 2 - 5 %>
        </p>

        <p>
          <strong>Int:</strong>
          <%= @character.intelligence %> |
          Mod:
          <%= @character.intelligence / 2 - 5 %>
        </p>

        <p>
          <strong>Wis:</strong>
          <%= @character.wisdom %> |
          Mod:
          <%= @character.wisdom / 2 - 5 %>
        </p>

        <p>
          <strong>Cha:</strong>
          <%= @character.charisma %> |
          Mod:
          <%= @character.charisma / 2 - 5 %>
        </p>
      <p>
        <strong>Initiative:</strong>
        <%= @character.initiative %>
      </p>

      <p>
        <strong>HP:</strong>
        <%= @character.hit_points %> |
        <strong>AC:</strong>
        <%= @character.armor_class %>
      </p>

      <p>
        <strong>PD:</strong>
        <%= @character.phys_def %> |
        <strong>MD:</strong>
        <%= @character.mental_def %>
      </p>

      <p>
        <strong>Recoveries:</strong>
        <%= @character.recoveries %>
      </p>

      <p>
        <strong>Recovery Dice:</strong>
        <%= @character.recovery_dice %>
      </p>

      <p>
        <strong>One Unique Thing:</strong>
        <%= @character.one_unique_thing %>
      </p>

      <p>
        <strong>Icons:</strong>
        <%= @character.icons %>
      </p>

      <p>
        <strong>Backgrounds:</strong>
        <%= @character.backgrounds %>
      </p>

      <p>
        <strong>Racial:</strong>
        <%= @character.racial %>
      </p>

      <p>
        <strong>Class features:</strong>
        <%= @character.class_features %>
      </p>

      <p>
        <strong>Talents:</strong>
        <%= @character.talents %>
      </p>

      <p>
        <strong>Basic Melee Attack:</strong>
        <%= @character.melee_atk %> |
        <strong>Basic Ranged Attack:</strong>
        <%= @character.ranged_atk %>
      </p>

      <p>
        <strong>Powers:</strong>
        <%= @character.powers %>
      </p>

      <p>
        <strong>Feats:</strong>
        <%= @character.feats %>
      </p>

      <p>
        <strong>Equipment:</strong>
        <%= @character.equipment %>
      </p>

      <p>
        <strong>Gold:</strong>
        <%= @character.gold %>
      </p>

      <p>
        <strong><%= link_to "Inventory", character_items_path(@character) %>:</strong>
        <% @character.items.each do |item| %>
          <%= item.name %>,
        <% end %>
      </p>

      <div>
        <%= link_to 'Back', characters_path %> |
        <%= link_to 'Edit', edit_character_path(@character) %>
      </div>
    </div>
  </div>
</div>