config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  resources :characters, shallow: true do
    resources :items
  end
  resources :room_characters
  resources :visitors
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :players, class_name: "RoomCharacter", foreign_key: "room_id"

  validates :name, :password, :gm_name, presence: true

  def self.search(params)
    where("name LIKE ? OR gm_name LIKE ?", "%#{params}", "%#{params}")
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    if params[:search].present?
      @rooms = Room.search(params[:search])
    else
      @rooms = Room.all
    end
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @join = RoomCharacter.new
    @characterids = @room.players.map(&:player_id)
    @characters = Character.find(@characterids)
    @players = User.find(@characters.map(&:user_id))
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.user = current_user

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :password, :gm_name)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= simple_form_for(@room) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.input :name, label: 'Room name' %>

    <%= f.input :password, label: 'Room password' %>

    <%= f.input :gm_name, label: "Your display name" %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<div>
  <% @rooms.each do |room| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= room.name %></h3>
      </div>
      <div class="panel-body">
        <p>
          GM: <%= room.gm_name %>
        </p>
        <br />
        <%= link_to 'View', room, class: "btn btn-default" %></td>
      </div>
    </div>
  <% end %>
</div>

<br>

<%= link_to 'Create a room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center"><%= @room.name %></h1>

<% if @room.user == current_user %>
  <p class="text-center">
    <strong>Password:</strong>
    <%= @room.password %> | <%= link_to 'Edit', edit_room_path(@room), class: 'text-center' %>
  </p>
<% end %>

<h3 class="text-center">GM:
  <% if @room.user == current_user %>
    You
  <% else %>
    <%= @room.gm_name %>
  <% end %>
</h3>

<% if @room.user.id != current_user.id %>
  <% if @players.map(&:id).include? current_user.id %>
  <% else %>
    <%= simple_form_for(@join) do |f| %>
      <%= f.hidden_field :room_id, value: @room.id %>
      <%= f.input :player_id, collection: current_user.characters.order(:name) %>
      <div class="form-actions">
        <%= f.submit "Join", class: "btn btn-info" %>
      </div>
    <% end %>
  <% end %>
<% end %>

<div class="row">
<% if @room.players.any? %>
  <% @room.players.each do |player| %>
    <div class="panel panel-default text-center col-md-3">
      <div class="panel-heading">
        <h3 class="panel-title"><%= player.player.name %></h3>
      </div>
      <div class="panel-body">
        <p>
          <strong>Class:</strong>
          <%= player.player.job %> |
          <strong>Race:</strong>
          <%= player.player.race %>
        </p>
        <p>
          <strong>Strength Mod:</strong>
          <%= player.player.strength / 2 - 5 %>
        </p>
        <p>
          <strong>Constitution Mod:</strong>
          <%= player.player.constitution / 2 - 5 %>
        </p>
        <p>
          <strong>Dexterity Mod:</strong>
          <%= player.player.dexterity / 2 - 5 %>
        </p>
        <p>
          <strong>Intelligence Mod:</strong>
          <%= player.player.intelligence / 2 - 5 %>
        </p>
        <p>
          <strong>Wisdom Mod:</strong>
          <%= player.player.wisdom / 2 - 5 %>
        </p>
        <p>
          <strong>Charisma Mod:</strong>
          <%= player.player.charisma / 2 - 5 %>
        </p>
        <p>
          <strong>Initiative:</strong>
          <%= player.player.initiative %>
        </p>
        <p>
          <strong>HP:</strong>
          <%= player.player.hit_points %> |
          <strong>AC:</strong>
          <%= player.player.armor_class %>
        </p>
        <p>
          <strong>PD:</strong>
          <%= player.player.phys_def %> |
          <strong>MD:</strong>
          <%= player.player.mental_def %>
        </p>
        <% if player.player.user_id == current_user.id %>
          <%= link_to "Remove", player, method: :delete %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>
</div>

<hr />

<%= link_to 'Back', rooms_path %>
<% if @room.user == current_user %>
  | <%= link_to 'Edit', edit_room_path(@room) %>
<% end %>