config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  resources :characters, shallow: true do
    resources :items
  end
  resources :room_characters
  resources :visitors
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :character

  validates :name, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_character, only: [:index, :new, :create]

  # GET /items
  # GET /items.json
  def index
    @items = @character.items
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = @character.items.build
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = @character.items.build(item_params)
    @item.character_id = @character.id

    respond_to do |format|
      if @item.save
        format.html { redirect_to character_items_path(@character), notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    character_id = @item.character_id
    @item.destroy
    respond_to do |format|
      format.html { redirect_to character_items_path(character_id), notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def set_character
      @character = Character.find(params[:character_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :stats, :uses, :gold_value, :character_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for [@character, @item] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.input :name %>

    <%= f.input :description %>

    <%= f.input :stats %>

    <%= f.input :uses %>

    <%= f.input :gold_value %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', character_items_path(@item.character_id) %>

app/views/items/index.html.erb
<p id="notice" class="text-center"><%= notice %></p>

<h1><%= link_to @character.name, @character %>'s Inventory</h1>

  <div class="row">
    <% @items.each do |item| %>
      <div class="col-md-3">
        <div class="panel panel-default">
          <div class="panel-body text-center">
            <td><strong><%= link_to item.name, item %></strong></td>
            <br />
            <td><%= item.description %></td>
            <br />
            <td>Stats: <%= item.stats %></td>
            <br />
            <% if item.uses %>
              <td>Uses: <%= item.uses %></td> |
            <% end %>
            <td>Value: <%= item.gold_value %></td>
            <br />
            <td><%= link_to 'Edit', edit_item_path(item) %></td>
            <td><%= link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </div>
        </div>
      </div>
    <% end %>
  </div>

<br>

<%= link_to 'New Item', new_character_item_path %>

app/views/items/new.html.erb
<div class="text-center">
  <h1>New Item</h1>

  <%= render 'form', character: @character, item: @item %>

  <%= link_to 'Back', character_items_path %>
</div>

app/views/items/show.html.erb
<p id="notice" class="text-center"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Stats:</strong>
  <%= @item.stats %>
</p>

<p>
  <strong>Uses:</strong>
  <%= @item.uses %>
</p>

<p>
  <strong>Gold value:</strong>
  <%= @item.gold_value %>
</p>

<p>
  <strong>Character:</strong>
  <%= @item.character.name %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Delete', @item, method: :delete, data: { confirm: "Are you sure?" } %> | 
<%= link_to 'Back', character_items_path(@item.character_id) %>